In [2]:
# python library ...numpy array is very faster then list .
#bcz its stored in contines memory.

In [3]:
!pip install Numpy

In [2]:
import numpy as np

In [5]:
list=[1,2,3,4]

In [6]:
type(list)

list

In [7]:
arr=np.array(list)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
z=np.ones(10)

In [11]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
a=np.array([1,2,3,4])

In [13]:
a


array([1, 2, 3, 4])

In [16]:
""" but it stored like 
1
2
3
4
like this way as 4 ROWS"""

' but it stored like \n1\n2\n3\n4\nlike this way as 4 ROWS'

In [17]:
a.size

4

In [20]:
a.ndim  # it give the dimensions


1

In [21]:
a.shape  #it give the no of rows and colomns

(4,)

# 2D ARRAY

In [96]:
b=np.array([[1, 2, 3, 4],[5,6,7,8],[1,4,5,6]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 4, 5, 6]])

In [28]:
b.ndim

2

In [29]:
b.size

12

In [30]:
b.shape

(3, 4)

# 3D ARRAY

In [102]:

s=b.reshape(3,2,2)
s

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[1, 4],
        [5, 6]]])

In [103]:
s.ndim

3

In [104]:
s.shape

(3, 2, 2)

# indexing

In [44]:
arr=np.array([1,2,3,4])

In [46]:
arr[1] #1d arary

2

In [47]:
#2d array 

In [48]:
a=np.array([[1,2,3],[2,3,4]])

In [49]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [56]:
a[1,2] # indexing from 0 to ... mind it

4

In [59]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [61]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.random.randint(0,6,9)

array([2, 2, 2, 5, 4, 0, 5, 3, 4])

In [72]:
np.random.rand(2,2)   #priting random matrix

array([[0.40934494, 0.78502688],
       [0.64582759, 0.33754311]])

In [80]:
# printing max and min values 





a

array([[1, 2, 3],
       [2, 3, 4]])

In [74]:
a.max()# max value

4

In [77]:
a.argmax() # index of max value 

5

In [79]:
a.min()

1

In [108]:
a=np.arange(1,10,2)# here 2 is required diff btw them

In [109]:
a

array([1, 3, 5, 7, 9])

# SLICING

In [110]:
a

array([1, 3, 5, 7, 9])

In [111]:
a[1:3]

array([3, 5])

In [4]:
import numpy as np
a=np.array([[1,2,3],[1,2,4],[7,8,9]])
a

array([[1, 2, 3],
       [1, 2, 4],
       [7, 8, 9]])

In [5]:
a[0:1,0:1]


array([[1]])

In [186]:
a[2:3,0:2]

array([[7, 8]])

In [187]:
a[0:2,1:3]

array([[2, 3],
       [2, 4]])

In [190]:

a[1:3,0:2]   

array([[1, 2],
       [7, 8]])

In [147]:
a[1:2,1:2]

array([[2]])

In [169]:
b=np.random.randint(1,12,5)

In [170]:
a

array([9, 2, 1, 7, 4])

In [171]:
b

array([ 7,  6,  5,  1, 11])

In [172]:
c=a+b

In [173]:
c

array([16,  8,  6,  8, 15])

In [176]:
c=np.sqrt(a)

In [177]:
c

array([3.        , 1.41421356, 1.        , 2.64575131, 2.        ])

In [8]:
a=np.arange(0,25,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
mat=np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
import numpy as np

mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
mat[0:3,0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
mat.ndim

2